json.id event.id
json.date event.date
json.time_of_day event.time_of_day
json.name event.name
json.description_level_1 event.description_level_1
json.description_level_2 event.description_level_2
json.description_level_3 event.description_level_3
json.location.id event.location.id
json.category.id event.category.id
json.year event.year